pre-commit:
  parallel: true
  commands:
    prettier:
      run: npx prettier --write --cache --ignore-unknown {staged_files}
      stage_fixed: true

    eslint:
      run: npx eslint --fix --cache --max-warnings=0 {staged_files}
      glob: "*.ts"
      stage_fixed: true

post-merge:
  commands:
    install:
      run: npm install

output:
  - summary
  - failure
