name: Dev Build - API

on:
  workflow_dispatch:
    inputs:
      notes:
        description: "Notes"
        required: false
        default: ""
  schedule:
    - cron: "0 0 * * *"

jobs:
  deploy-dev-api:
    name: Deploy to dev
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org/"
          cache: npm
      - run: npm ci
      - run: npm update @mdn/browser-compat-data
      - run: npm run generate
      - name: Configure AWS credentials for dev
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_ACCESS_KEY_SECRET }}
          aws-region: us-west-2
      - run: aws s3 sync --acl public-read out/ s3://mdn-content-dev/main/bcd/api/
      - run: aws s3 sync --acl public-read --delete out/v0/current s3://mdn-content-dev/main/bcd/api/v0/current
      - name: Invalidate CDN
        env:
          DISTRIBUTION: E9813D0RN1QZI
          PATHS: /bcd/api/*
        run: aws cloudfront create-invalidation --distribution-id "$DISTRIBUTION" --paths "$PATHS"
