name: Test

on:
  push:
    branches:
      - main
  pull_request:

# No GITHUB_TOKEN permissions, as we don't use it.
permissions: {}

jobs:
  root:
    if: github.repository == 'mdn/bcd-utils'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

  api:
    if: github.repository == 'mdn/bcd-utils'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: api/package-lock.json

      - name: Install
        working-directory: api/
        run: npm ci

      - name: Build
        working-directory: api/
        run: npm run build

      - name: Test
        working-directory: api/
        run: npm run test

  updates:
    if: github.repository == 'mdn/bcd-utils'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: updates/package-lock.json

      - name: Install
        working-directory: updates/
        run: npm ci
